### ISSUE TITLE
Dependencies not updated using `python setup.py develop`.

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#156]
@SBeijen and I both seem to have problems with `progressbar2` not being installed and/or updated with setuptools: `python setup.py develop`.

It seems that, after a `git clone` (or sync), installing using `pip install .` does work. (For progressbar pip seems to fetch a wheel from pypi while setuptools downloads a tarball from pypi and tries to build an egg and install that, which fails).

"Looking around" it seems `pip install .` might be better dan using setuptools. I think we must consider switching to pip. 

`pip install .` does the same as `python setup.py develop`: It does not install the package to `../site-packages/` but adds the current location of the package to `sys.path`.

**Comment by 153957** [comment]
I looked around a bit about the difference, have not yet found exactly what the advantages vs disadvantages are. I do see that some that show the `pip` way also use the `-e` flag, which does:
```
  -e, --editable <path/url>   Install a project in editable mode (i.e. setuptools
                              "develop mode") from a local project path or a VCS url.
```
I do not see exactly how that would differ, since you say that without it it also does not install the package in site-packages..

**Comment by tomkooij** [comment]
Since  `pip install progressbar` solves problems with installing progressbar in `python setup.py develop` (only the first install) this seems not needed.

Let's not bother.
