### ISSUE TITLE
Replace slow read_where() with faster read_where() and compress() in GroundParticleSimulation() class

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#56]
GroundParticleSimulation is slow. It spends 99% of its execution time in a pytables query: 

```python 
query = ('(x >= %f) & (x <= %f) & (y >= %f) & (y <= %f)'
                 ' & (particle_id >= 2) & (particle_id <= 6)' %
                 (x - detector_boundary, x + detector_boundary,
                  y - detector_boundary, y + detector_boundary))
        return self.groundparticles.read_where(query)
```
This is slow because we query over multiple columns. 

Using read_where() for y (faster than x, probably because of sorting?) and subsequently using numpy.compress() to select for x is **4x faster** in testing. Perhaps even faster when also inclusing particle_id. The compress() part can be done from a numpy.array that fits in L2 cache (or even in L1 cache.)

```python 
def test_query_compress(N):
    """ read_where() query in y, compress() for x selection """
    coordinates = SCALE*np.random.randn(N,2)
    for x,y in coordinates:
        query_y = '(y >= %f) & (y <= %f)' % (y,y+0.5)
        selection = groundparticles.read_where(query_y)
        sel = selection.compress((selection['x'] >= x) & (selection['x'] <= x+0.5))
        print len(sel)
```

**Comment by 153957** [comment]
I have not yet tried using compress. I did perform some simple benchmarks with read_where; https://github.com/HiSPARC/sapphire/pull/15#issuecomment-34163443
One of the important factors in the speed of the query is the number of particles returned. Note that the corsika h5 files have an index for the x column, so using read_where for the x column and filter y using compress might be faster. Indexing can be beneficial and sometimes detrimental, it varies on a case by case basis, also depending on the number of particles returned...

We will need to do some 'real-world' tests to properly compare the final speed. I.e. one or multiple showers (1e15-1e17 eV) for a typical cluster (e.g. Science Park) at a reasonable maximum core distance (~600 m for Science Park) for a certain number of core positions and directions (200?)..

**Comment by tomkooij** [comment]
It turns out actually **sorting** the datafile with respect to the indexed column helps a lot:
http://stackoverflow.com/questions/17868693/optimizing-a-complex-table-where-query-in-pytables

A quick tests results in another 4x speedup. In this simple test sorting and read_where()+compress() is **>15x faster** than a complex read_where() on unsorted hdf5!.

**Comment by 153957** [comment]
Ah of course sorting would reduce the number of chunks (parts of the h5 file) that would need to be read into memory. h5 files are chunked into pieces, (Im not entirely sure how it works, but I suppose something like this) every x rows go into a chunk, if you need to read one row from each chunk you need to read all those chunks into memory, including many rows that you don't use. So for small showers that fit into RAM this might not be a big problem, since we query the table multiple times, so we would likely need the entire file in RAM anyway.. But there might still be a speed improvement when the file is sorted. Ok, we'll have to properly investigate this, setup a representative benchmark: simulations like I mentioned before and test several ways of storing the CORSIKA data combined with the different ways of querying the data.

**Comment by 153957** [comment]
In 4112bf4ce14a6b839df3ad809d402ec07918aa77 you overwrote the 'old' algorithm with the new read_where/compress variant.
In order to more easily test the differences you can keep the 'old' one around in a new class, just like we did with the more precisie detector boundary simulation:
https://github.com/HiSPARC/sapphire/blob/4112bf4ce14a6b839df3ad809d402ec07918aa77/sapphire/simulations/groundparticles.py#L306

**Comment by tomkooij** [comment]
Will do!

**Comment by davidfokkema** [comment]
Good work, Tom. Maybe you should consider filing a bug report against PyTables. I should think that a read_where query should always be fast. Doing some work on structuring the index, the query, and making use of compress should be able to squeeze an extra bit of speed out of the query, but not a factor of 16. Either we were doing something seriously wrong, or this should warrant *at least* a helpful paragraph in the package documentation of PyTables.

**Comment by tomkooij** [comment]
Biggest improvement: physically sort data in x (ptrepack --sortby=x ...) and add csindex in x
Splitting read_where in read_where() and subsequent_compress is about 30% faster.

Code is in "pytables_query branch": 62c983f53f3c5a7b4f9573e2f8cbbcd080831c6f
Test script is in: https://gist.github.com/tomkooij/7d5594f61ae8394e7562 (running now with N=1000 on stoomboot, data to follow)

**Comment by 153957** [comment]
Ok, clearly sorting is the biggest improvement.
I will make a new branch form sapphire to update `store_corsika_data` to first convert the data to a temporary h5 file (they way they are created now, unsorted, but with csindex) and then use `Leaf.copy` with `sortby` to create a new h5 sorted version, and also use blosc compression...

Information about sorted tables: https://pytables.github.io/usersguide/optimization.html#achieving-ultimate-speed-sorted-tables-and-beyond

**Comment by 153957** [comment]
See the PR #57 for the new `store_corsika_data` that also sorts the `corsika.h5`. I chose not to enable `blosc` because it did seem to help much.

In my test on a 380MB file the sorted version was __50x faster__.
So, this should really help for those large showers!

Should we also use compress or perhaps also index y?

**Comment by davidfokkema** [comment]
Blosc did not improve performance-wise, but does it matter for the amount of storage required?

**Comment by 153957** [comment]
As can be seen in #57 the size was slightly better (15 %) using complevel 9, but the performance degraded (~10 %).

**Comment by davidfokkema** [comment]
Oops. Missed that.
