### ISSUE TITLE
Cluster object no longer stored  in _v_attrs but used in reconstructions. 

### ISSUE THREAD

**Issue by tomkooij** [HiSPARC/sapphire#89]
esd.py used to store cluster objects in table._v_parent._v_attrs. The sizeof a cluster object can become too large for _v_attrs when downloading data for large clusters. (max 64kb attributes per HDF5 file, https://www.hdfgroup.org/HDF5/faq/limits.html).

Writing cluster object to _v_attrs was removed in esd.py in bd8c29d2001442eccbd1c9119553f567f8859cf8 . 

Issue: cluster objects are read from _v_attrs in reconstructions: https://github.com/HiSPARC/sapphire/blob/master/sapphire/analysis/reconstructions.py#L227

**Comment by 153957** [comment]
Instead of getting an existing cluster object and making a new one with the station numbers it keeps the existing cluster object. This is because simulations may use fake clusters, but each station still gets a number (if not given it will be the station id). Moreover, the simulations do not yet have a good sense of time (4D cluster), so also with real stations one must be careful..
